### ISSUE TITLE
Setup information

### ISSUE THREAD

**Issue by ellis2323** [vulcanize/vulcanizedb#110]
Hello,

As the Ethereum blockchain size is huge (full sync > 100Go), i would known the size needed to store the ethereum blockchain with vulcanizeDB. I didn't find anything related in requirement. I could be great to give us some words about time and size needed for a complete setup.

Thanks

**Comment by rmulhol** [comment]
Hi @ellis2323,

It really depends on your use case.

If you run `headerSync` + `contractWatcher`/`composeAndExecute`, then the requirements are low - because you're only caching a subset of block headers, transactions, event logs, and/or storage trie nodes (i.e. the ones you specify in your config).

If you run `fullSync`, then the requirements are high - because you're extracting and indexing _all_ of the blocks, transactions, receipts, and event logs.

I would strongly recommend getting started with option 1. But even in that case, there will be variation depending on how many contracts you're tracking, how much on chain activity happens on those contracts, whether you choose to cache contract state alongside events, and so forth.

Happy to answer any further questions!

**Comment by i-norden** [comment]
Hi @pvle2017, could you shared the `metalith.toml` config with us? Would help greatly in getting to the bottom of this issue, thank you!

**Comment by rmulhol** [comment]
@i-norden I think we resolved the `metalith` issue when we addressed #135 

Can probably go ahead and close this one unless @ellis2323 has further questions?
