### ISSUE TITLE
cannot find package "github.com/ethereum/go-ethereum/statediff"

### ISSUE THREAD

**Issue by jmahhh** [vulcanize/vulcanizedb#169]
Hi, when running `go get github.com/vulcanize/vulcanizedb` I get:
```
package github.com/ethereum/go-ethereum/statediff: cannot find package "github.com/ethereum/go-ethereum/statediff" in any of:
	/usr/lib/go/src/github.com/ethereum/go-ethereum/statediff (from $GOROOT)
	/home/joel/go/src/github.com/ethereum/go-ethereum/statediff (from $GOPATH)
```

I can still run `make build`, but not sure how the above influences the install?

**Comment by i-norden** [comment]
Hi @jmahhh !

We are using a custom fork of go-ethereum that provides that `statediff` pkg: https://github.com/vulcanize/go-ethereum/releases/tag/v1.10-alpha.0

If you are using Go modules, `make build` correctly builds with this version of go-ethereum, but it appears you are getting the warning when you `go get github.com/vulcanize/vulcanizedb` because this version of go-ethereum is not present at your local $GOPATH.
