### ISSUE TITLE
Persist content addressable transaction history

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#31]
As an applicant developer using Vulcanize,
I want to be able to query for IPLD data representing a contract's history,
So that I have content addressable data to validate the result sets generated by my queries.

Notes
- Requires converting Ethereum data into IPLD and persisting it to Postgres
- Requires constructing a relational representation of that data for optimized queries

Comments
- Perhaps an alternative "So that" rationale - are we actually preferring IPLD data because it allows us to extend what types of data we persist, rather than to validate queries?

**Comment by AFDudley** [comment]
I have made some slight tweaks to the above.

> Perhaps an alternative "So that" rationale - are we actually preferring IPLD data because it allows us to extend what types of data we persist, rather than to validate queries?

hmm. Yes and no.
No. We are using IPFS/IPLD because a lot of the mechanical work in defining the transformations has already been done there.  

But yes, in the sense that the merkle graph that IPFS generates is useful to application developers who are using vDB.

**Comment by rmulhol** [comment]
Closing as this is partially addressed by `syncAndPublish`
