### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by jeffersondarcy** [vulcanize/vulcanizedb#40]
I am trying to understand how VulcanizeDB works.
From what I understand it copies data from blockchain to PostgreSQL database. What is vulcanizedb sync doing, is it constantly feeding new transactions to postgre or is it doing a snapshot - is it constantly running or needs to be scheduled?  
How should I deal with new transactions so I can be sure they are final - should I just ignore the 12 latest blocks, or what's the recommended strategy? 
Do I query directly the postgreSQL with my queries? Do I need to/can I do any schema modifications for specific indicies or just use the default?
Can I use Amazon Aurora instead of Postgre?
Is it possible/necessary to run two ethereum clients - geth and parity to have the better certainty about transactions or is this setup not intended?

Is VulcanizeDB production ready for use on exchanges - what are the limitations?

**Comment by i-norden** [comment]
Hi @jeffersondarcy thank you for the questions! There has been a significant overhaul since this was posted, and I hope some of these questions are adequately addressed in the documentation now. In any case, in regards to your specific questions:

Q: From what I understand it copies data from blockchain to PostgreSQL database. What is vulcanizedb sync doing, is it constantly feeding new transactions to postgre or is it doing a snapshot - is it constantly running or needs to be scheduled?

A: The current sync modes are described in detail [here](https://github.com/vulcanize/vulcanizedb/blob/staging/documentation/data-syncing.md). The fullSync is a continuous import of all block data (headers, transactions, receipts, and logs) over json-rpc, the headerSync is a continuous import of only headers over json-rpc, and coldImport is a fullSync analog that imports all data from the underlying leveldb (snapshot). 

Q: How should I deal with new transactions so I can be sure they are final - should I just ignore the 12 latest blocks, or what's the recommended strategy?

A:  Yes, ignore blocks/transactions that are more recent than your desired number of confirmations. The sync processes validate a configurable number of blocks/headers and should remove any that change within that window, which will cascade delete transactions and related data. Blocks are marked as `final` after they've made it past the validation window.

Q: Do I query directly the postgreSQL with my queries? Do I need to/can I do any schema modifications for specific indicies or just use the default?

A: The answer depends on how you are using Vulcanizedb and for what purpose. The various sync modes sync raw Ethereum data in Postgres, this can be queried directly or it can be used to direct further data transformations (using [custom transformers](https://github.com/vulcanize/vulcanizedb/blob/staging/documentation/custom-transformers.md) or the [built-in one](https://github.com/vulcanize/vulcanizedb/blob/staging/documentation/generic-transformer.md)). For custom transformations you will need to create the appropriate schemas/tables, for the generic ones this is handled under the hood.

Q: Can I use Amazon Aurora instead of Postgre?

A: No, at this time it only supports Postgres.

Q: Is it possible/necessary to run two ethereum clients - geth and parity to have the better certainty about transactions or is this setup not intended?

A: Currently vDB is designed to sync data from a single Ethereum client (either Parity or Geth), in the future we would like for it to work as you described, with a mechanism for resolving discrepancies between the Geth and Parity data but this still needs to be worked out.

Q: Is VulcanizeDB production ready for use on exchanges - what are the limitations?

A: VulcanizeDB is still in its 0.0.x versions and is undergoing a lot of changes, whether or not it is suited for a production environment will depend on the specifics of that environment and what role vulcanizeDB is serving. Would be happy to discuss this further if you can provide some additional context for your use case!

**Comment by rmulhol** [comment]
Closing in light of the replies above - feel free to reach out if you have any additional questions!
