### ISSUE TITLE
Geth hot import

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#54]
As an application developer setting up vulcanize db,
I want to be able to import core vulcanize data from a running instance of level db,
So that I can realize the performance gains of level db access without pausing node syncing.

**Notes**
Seems possible by initializing a `Blockchain` object: https://github.com/ethereum/go-ethereum/blob/master/core/blockchain.go

**Comment by hermanjunge** [comment]
Here https://github.com/ethereum/go-ethereum/compare/master...MetaMask:feat/getLevelDbKey

Started working on that, turns out that looking into the right direction, is easy to export a method `debug.getLevelDbKey` to be exposed in **geth** RPC  with the flags `--rpcapi eth,debug`.

My testing has been done with a light client so far, and cannot figure out why I cannot geth the state root, I suspect it is something relating with prefix maybe? That's my current blocked, to have this fork operational.

My next steps in mustekala would be:

* Making available the query of state (and storage) trie subsets. For example *"give me, starting from root 0xblabla.. their children in 3 levels"*.

* Then I was checking geth has a debug function to see which addressed have changed
  * https://github.com/ethereum/go-ethereum/blob/eaff89291ce998ba4bf9b9816ca8a15c8b85f440/internal/web3ext/web3ext.go#L377
  * https://github.com/ethereum/go-ethereum/blob/eaff89291ce998ba4bf9b9816ca8a15c8b85f440/eth/api.go#L439
  * So, I'm thinking on something similar, where you ask, based on this result, which elements of the DB are new, so you can make a single one call retrieval.

@rmulhol Let me know what do you think. I'm very partial to have a relatively simple fork of geth, so we can set up parallel cheap agents, extracting data from the clients and making it available over IPFS, being by `add` + `pin` over a cluster, or by running an optimized node.

**Comment by hermanjunge** [comment]
+ @kumavis @dryajov @AFDudley

**Comment by rmulhol** [comment]
Hi @hermanjunge - thanks for chiming in!

Definitely on board with putting together a simple Geth forth that exposes an RPC method for fetching the state, and it would be awesome if we could figure out which paths have changed so that we don't have to walk the whole trie when attempting to cache the data in IPFS/VulcanizeDB.

I'd be tempted to premise the initial stab at this on the assumption that the user is running an archive node, as it seems that Geth's state trie pruning is a bit more aggressive than Parity's - I get a `missing trie root` error for state roots corresponding to all but the most recent (~2) blocks on non-archive clients.

**Comment by i-norden** [comment]
The [seed node](https://github.com/vulcanize/vulcanizedb/pull/114) and [state-diffing Geth](https://github.com/vulcanize/go-ethereum/pull/10) work are similar efforts to those described here but there are some deviations, mainly that we are not extracting data from the leveldb of an archival node but are streaming diffed state and storage data (as well as the rest of the block data) out of Geth as a full sync progresses. 

@hermanjunge I am curious what you think about these efforts, feedback on how we might further tailor this work to support your needs would be greatly appreciated!

**Comment by i-norden** [comment]
@rmulhol do you think this can be closed per the above comment?

**Comment by rmulhol** [comment]
@i-norden good with me 👍

**Comment by i-norden** [comment]
Closing per the above :)
