### ISSUE TITLE
Add description of function to README

### ISSUE THREAD

**Issue by wanderingstan** [vulcanize/vulcanizedb#60]
I was recommended this project as a tool for indexing blockchain data, perhaps similar to thegraph.com. It looks impressive, but from the Readme it's not quite clear what vulcanizedb actually does. E.g. does it put the _entire_ contents of the eth blockchain into postgres? What is the interface for accessing the data? 

Just a little "What it does" section would be very helpful!

EDIT: Found this comment on gitter with nice initial description:
https://gitter.im/vulcanizeio/VulcanizeDB?at=5b2a54b0148056028591b323
Opened PR with that text as about section: https://github.com/vulcanize/vulcanizedb/pull/61

More detail would still be appreciated.

**Comment by i-norden** [comment]
Closing this as documentation has been expanded upon vastly since this was opened. We don't have an "About" section in our readme, as we are trying to abide by the [standard](https://github.com/RichardLitt/standard-readme), but the [background](https://github.com/vulcanize/vulcanizedb#background), [usage](https://github.com/vulcanize/vulcanizedb#usage), and [separate individual docs](https://github.com/vulcanize/vulcanizedb/tree/staging/documentation) should hopefully answer your questions.
